import 'dart:io';
import 'package:get/get.dart';
import 'package:flutter/foundation.dart';
import '../../core/models/api_provider.dart';
import '../ai_provider.dart';
import 'dart:convert';

import '../../controllers/settings_controller.dart';
import '../gemini_service.dart';
import '../../core/utils/json_utils.dart';

class GeminiAudioService extends GetxService {
  final _geminiService = AIProviderFactory.getServiceByType(ProviderType.gemini);

  Future<Map<String, dynamic>> analyzeAudio(File videoFile) async {
    // 1. Prepare video bytes
    final bytes = await videoFile.readAsBytes();

    // 2. Prompt for Analysis
    final prompt = """
      استمع إلى الصوت في هذا الفيديو وقم بتحليله.
      أحتاج الناتج بتنسيق JSON حصراً (بدون ماركداون):
      {
        "audio_type": "voice" أو "music" أو "mixed" أو "noise",
        "voice_gender": "male" أو "female" أو "child" (إذا وجد صوت),
        "music_details": "نوع الموسيقى (Pop, Rock, etc.)" (إذا وجدت),
        "quality_issues": ["noise", "low_volume", "echo"],
        "suggested_actions": [
           {"id": "voice_female", "label": "تحويل لصوت أنثوي", "filter_desc": "pitch shift up"},
           {"id": "boost_vol", "label": "تضخيم الصوت", "filter_desc": "volume boost"},
           {"id": "remove_noise", "label": "إزالة الضوضاء", "filter_desc": "highpass/lowpass"}
        ]
      }
      يجب أن تكون الاقتراحات منطقية بناءً على التحليل (مثلاً لو الصوت رجل اقترح تحويل لامرأة أو طفل).
    """;

    try {
      final settings = Get.find<SettingsController>();
      final apiKey = settings.getApiKey(ProviderType.gemini);
      if (apiKey.isEmpty) throw Exception("يرجى تفعيل مفتاح Gemini في الإعدادات");
      
      final result = await _geminiService.analyzeImage(bytes, prompt, apiKey: apiKey);
      return JsonUtils.parseSafe(result.description);
    } catch (e) {
      debugPrint("Audio Analysis Error: $e");
      String errorMsg = "فشل تحليل الصوت: $e";
      if (e.toString().contains('Quota') || e.toString().contains('429')) {
         errorMsg = "تم تجاوز حد الاستخدام المجاني (Quota Exceeded) لـ Gemini. يرجى المحاولة لاحقاً.";
      }
      // We don't have a way to return an error object easily without breaking the Map return,
      // but we can log it carefully or throw a specific error if we wanted to show a snackbar.
      // For now, let's keep it robust and return the dummy but with the right log.
      return {
        "audio_type": "error",
        "error": errorMsg,
        "suggested_actions": [
          {"id": "boost_vol", "label": "تضخيم الصوت (احتياطي)"}
        ]
      };
    }
  }

  Future<String> getAudioFilterCommand(String actionId, Map<String, dynamic> analysis) async {
    // We ask Gemini to convert the Intent ID into an FFmpeg Filter String
    // This allows dynamic/complex filter logic generated by AI
    
    final prompt = """
      لدي ملف فيديو، وأريد تطبيق فلتر FFmpeg على الصوت (Audio Filter -af).
      
      تحليل الصوت السابق: ${jsonEncode(analysis)}
      الإجراء المطلوب (Action ID): "$actionId"

      أعطني فقط نص الفلتر (Filter String) لاستخدامه مع flag -af.
      لا تعطي أمر ffmpeg كامل، فقط السلسلة النصية للفلتر.
      
      ⚠️ تحذير: تجنب استخدام فلاتر معقدة مثل "curves" لأنها قد تسبب خطأ في الإحداثيات.
      استخدم الفلاتر الأساسية والقوية:
      - لتحسين الصوت (Studio): highpass=f=200, lowpass=f=3000, afftdn
      - لرفع الصوت (Boost): volume=2.5
      - لتغيير النبرة (Anonymize/Deep): asetrate=44100*0.85, aresample=44100, atempo=1.1
      
      الناتج يجب أن يكون نصاً واحداً بسيطاً ومباشراً بدون علامات تنصيص.
    """;

    try {
      final (provider, apiKey, _) = await AIProviderFactory.getSmartProvider();
      
      // If the smart provider isn't Gemini (e.g. user selected OpenAI), we might want to force Gemini 
      // since this service is specifically "GeminiAudioService". 
      // But for now, let's use the active one if compatible, or fallback to fetching Gemini key specifically.
      
      String keyToUse = apiKey;
      AIProvider providerToUse = provider;

      if (provider is! GeminiService) {
          // Force Gemini if the active one isn't Gemini (since prompt engineering is tuned for it?)
          // actually the prompt is generic enough, but let's stick to the class name implication.
          final settings = Get.find<SettingsController>();
          keyToUse = settings.getApiKey(ProviderType.gemini);
          if (keyToUse.isEmpty) throw Exception("مفتاح Gemini غير موجود");
          providerToUse = _geminiService;
      }

      final result = await providerToUse.generateText(prompt, apiKey: keyToUse);
      return result.description.trim().replaceAll('"', '').replaceAll("'", "");
    } catch (e) {
       // Fallback filters
       if (actionId.contains("female")) return "asetrate=44100*1.2,aresample=44100,atempo=1/1.2";
       if (actionId.contains("boost")) return "volume=2.0";
       return "volume=1.0";
    }
  }

  /// 🗣️ Generate Timed Subtitles (Speech to Text)
  Future<List<Map<String, dynamic>>> generateSubtitles(File videoFile) async {
    final bytes = await videoFile.readAsBytes();
    
    final prompt = """
      قم بتحويل الكلام في هذا الفيديو إلى نصوص (Subtitles) مع التوقيت الدقيق.
      أحتاج الناتج بتنسيق JSON حصراً كقائمة من الكائنات:
      [
        {"start_ms": 1000, "end_ms": 3000, "text": "مرحباً بكم في فيديو اليوم"},
        {"start_ms": 3500, "end_ms": 6000, "text": "سنتعلم كيف نستخدم الذكاء الاصطناعي"}
      ]
      شروط الرد:
      - توقيت البداية والنهاية بالميلي ثانية (ms).
      - أعد JSON فقط بدون أي ماركداون أو شرح.
    """;

    try {
      final settings = Get.find<SettingsController>();
      final apiKey = settings.getApiKey(ProviderType.gemini);
      
      final result = await _geminiService.analyzeImage(bytes, prompt, apiKey: apiKey);
      final List<dynamic> decoded = JsonUtils.parseListSafe(result.description);
      return decoded.map((e) => e as Map<String, dynamic>).toList();
    } catch (e) {
      debugPrint("Subtitle Generation Error: $e");
      return [];
    }
  }
}
